services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
    container_name: HR-Pulse-backend
    restart: always
    env_file:
      - .env
    environment:
      - AZURE_DB_URL=${AZURE_DB_URL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - "8000:8000"
    depends_on:
      - jaeger
    networks:
      - hr-pulse-network

  frontend:
    build:
      context: ../HR-Pulse-Frontend/hr-pulse-app
      dockerfile: Dockerfile
    container_name: HR-Pulse-frontend
    ports:
      - "3001:3000" 
    restart: always
    
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - hr-pulse-network
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" 
      - "4317:4317"   
    networks:
      - hr-pulse-network
  
networks:
  hr-pulse-network:
    driver: bridge