services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: HR-Pulse-backend
    restart: always
    env_file:
      - .env
    environment:
      - AZURE_SQL_URL=mssql+pyodbc://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}?driver=ODBC+Driver+18+for+SQL+Server
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./ml_models:/app/ml_models
    working_dir: /app
    command: >
      sh -c "sleep 5 && uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: ../HR-Pulse-Frontend/hr-pulse-app
      dockerfile: Dockerfile
    container_name: HR-Pulse-frontend
    ports:
      - "3000:3000" 
    restart: always
    volumes:
      - ../HR-Pulse-Frontend/hr-pulse-app:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend